// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $form_index from "./routes/form/index.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Echoer from "./islands/Echoer.tsx";
import * as $Input from "./islands/Input.tsx";
import * as $Message from "./islands/Message.tsx";
import * as $SubscribeForm from "./islands/SubscribeForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/joke.ts": $api_joke,
    "./routes/form/index.tsx": $form_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Echoer.tsx": $Echoer,
    "./islands/Input.tsx": $Input,
    "./islands/Message.tsx": $Message,
    "./islands/SubscribeForm.tsx": $SubscribeForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
